# This sets the name of your application to pulse.
spring:
  application:
    name: pulse
  messages:
    basename: ValidationMessages
    encoding: UTF-8

# Server configuration
server:
  port: 8182

# Defines application prefix
pulse:
  api:
    prefix: /api

# Enables Spring Boot Actuator’s health endpoint to show detailed status
management:
  endpoint:
    health:
      show-details: always

