server:
  port: 8081
spring:
  application:
    name: pluse
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    name: logs/app.log
  config: classpath:logback-spring.xml
